### ISSUE TITLE
Screeps server url should be configurable option

### ISSUE THREAD

**Issue by Tokeiito** [screepers/screeps_console#11]
This will help to support local server installations. Also need to determine what requirements are to support terminal for local server installation.

**Comment by tedivm** [comment]
Pull requests are accepted :-)

**Comment by Tokeiito** [comment]
ok. Heh sadly i eat my bread with Java not with Python ;) Is Screepsapi third party library or not? As those hardcoded url's are there.

**Comment by tedivm** [comment]
Yeah, it's thirdy party. However, someone made a pull request already for it to support other servers.

**Comment by bastianh** [comment]
I have created a pull request that allows connection to private servers #13

**Comment by Tokeiito** [comment]
As pull request was made and merged i'm closing this issue.
