### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by EnderInvader** [screepers/screeps_console#23]
I am confused on how the install the screeps console, and I can't get it to work, I get through the first few steps, but then the source command and make commands don't do anything. Am I missing something that I am supposed to do?

**Comment by tedivm** [comment]
Literally nothing outputs from the make commands? Can you go into some more detail about what OS you have, what version of python, etc?

**Comment by EnderInvader** [comment]
What I mean by nothing happens is that when I put in the commands I get an error saying the command is not recognized. I am using Windows 10, and I am using python 3.6, here is exactly what I did: I downloaded virtualenv via pip, I cloned the code and also downloaded it to a zip file, I then located the .exe of my python (3.6), I put the command ‘virtualenv -p [path to python exe] env’, into the command prompt and it seemed to work fine, but when I put in the command ‘source env/bin/activate’ it threw an error of ‘unknown command source’, and it did the same when I put in the make commands. I tried a bunch of different ways of setting up the files and inputing the commands, but all I would get is errors. I did nodice that I didn’t have cygwin, so I went and downloaded that, and redid the steps, but I got the same errors. Am I supposed to do something with cygwin?

**Comment by tedivm** [comment]
Sorry, I don't use Windows so I don't really support it as an option. I know other people have gotten it working on Windows (using either cygwin or the linux subsystem available on newer versions of Windows), so it's definitely possible, but you're going to have to put some leg work in figuring out how to run python applications in a windows environment.

If you do get it working feel free to make a pull request to update the docs so future users don't face the same troubles you have. It's possible @ags131 may be able to provide some guidance as well.

**Comment by AlinaNova21** [comment]
I haven't used it on windows, my solution has been to ssh into a linux box and run it from there. (I use cygwin for ssh). Although, @Dessix did get it working directly in windows IIRC. It may also be possible to run it through WSL, although I personally haven't tried yet.

**Comment by Dessix** [comment]
It was through WSL when I did it.

**Comment by EnderInvader** [comment]
@tedivm I've been trying and I haven't been able to get it to work, would there be a way I could make my own? Are there docs or something for making this stuff?

**Comment by tedivm** [comment]
[Node API Library](https://github.com/screepers/node-screeps-api)

[Python API Library](https://github.com/screepers/python-screeps)

[Semi Outdated API Docs](https://github.com/screepers/python-screeps/blob/master/docs/Endpoints.md)
